spring.application.name=gateway-service

server.port=8080

# Compte technique permettant d'accéder à la Gateway
security.service.username=${SECURITY_USERNAME:medilabo-service}
security.service.password=${SECURITY_PASSWORD:medilabo-password}

# Route vers patient-service
spring.cloud.gateway.routes[0].id=patient-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/patients/**

# Route vers note-service
spring.cloud.gateway.routes[1].id=note-service
spring.cloud.gateway.routes[1].uri=http://localhost:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/notes/**

# Route vers assessment-service
spring.cloud.gateway.routes[2].id=assessment-service
spring.cloud.gateway.routes[2].uri=http://localhost:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/assessments/**