spring.application.name=assessment-service

server.port=8084

patient.service.url=http://patient-service:8081
note.service.url=http://note-service:8083

security.service.username=${SECURITY_USERNAME:medilabo-service}
security.service.password=${SECURITY_PASSWORD:medilabo-password}

security.client.username=${SECURITY_CLIENT_USERNAME:medilabo-service}
security.client.password=${SECURITY_CLIENT_PASSWORD:medilabo-password}