spring.application.name=assessment-service

server.port=8084

patient.service.url=http://patient-service:8081
note.service.url=http://note-service:8083

security.service.username=${SECURITY_USERNAME}
security.service.password=${SECURITY_PASSWORD}

security.client.username=${SECURITY_CLIENT_USERNAME}
security.client.password=${SECURITY_CLIENT_PASSWORD}