spring.application.name=front-service

server.port=8082

# Adresse de la Gateway en environnement local
gateway.url=http://localhost:8080

# Compte technique envoyé par le front à la Gateway
security.client.username=${SECURITY_CLIENT_USERNAME:medilabo-service}
security.client.password=${SECURITY_CLIENT_PASSWORD:medilabo-password}