spring.application.name=front-service

server.port=8082

# Nom du service Docker de la Gateway
gateway.url=http://gateway-service:8080

# Compte technique récupéré depuis Docker
security.client.username=${SECURITY_CLIENT_USERNAME}
security.client.password=${SECURITY_CLIENT_PASSWORD}