spring.application.name=front-service

server.port=8082

gateway.url=http://localhost:8080

security.client.username=${SECURITY_CLIENT_USERNAME:medilabo-service}
security.client.password=${SECURITY_CLIENT_PASSWORD:medilabo-password}