spring.application.name=patient-service

server.port=8081

spring.datasource.url=jdbc:mysql://mysql:3306/medilabo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Identifiants récupérés depuis les variables d'environnement Docker
security.service.username=${SECURITY_USERNAME}
security.service.password=${SECURITY_PASSWORD}